---
- name: PHP configureation file transfer
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}/{{ item.src }}'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - { src: 'php.ini',      dest: '/etc/' }
    - { src: 'php-fpm.conf', dest: '/etc/' }
    - { src: 'www.conf',     dest: '/etc/php-fpm.d' }
  register: php_config
