---
- name: Set PHP binary PATH parameters
  lineinfile:
    dest: '/etc/profile'
    state: 'present'
    regexp: '^source /opt/remi/php'
    line: 'source /opt/remi/php{{ php_version }}/enable'

- name: PHP-FPM systemd service file modify
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/php{{ php_version }}-php-fpm.service'
    insertafter: '\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^LimitNOFILE=',  line: 'LimitNOFILE=65535' }
    - { regexp: '^LimitNPROC=',   line: 'LimitNPROC=65535' }
    - { regexp: '^LimitCORE=',    line: 'LimitCORE=infinity' }
    - { regexp: '^LimitMEMLOCK=', line: 'LimitMEMLOCK=infinity' }
  register: php_service

#- name: PHP configureation file transfer
#  template:
#    src: '{{ php_version }}/{{ item.src }}'
#    dest: '{{ php_conf_path }}/{{ item.dest }}'
#    owner: root
#    group: root
#    mode: 0644
#  with_items:
#    - { src: 'php.ini.j2',      dest: '/php.ini' }
#    - { src: 'php-fpm.conf.j2', dest: '/php-fpm.conf' }
#    - { src: 'www.conf.j2',     dest: '/php-fpm.d/www.conf' }
#  register: php_config
