---
- name: Set PHP binary PATH parameters
  lineinfile:
    dest: '/etc/profile'
    state: 'present'
    regexp: '^source /opt/remi/php'
    line: 'source /opt/remi/php{{ php_version }}/enable'

- name: PHP-FPM systemd service file modify
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/php{{ php_version }}-php-fpm.service'
    insertafter: '\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - { regexp: '^LimitNOFILE=',  line: 'LimitNOFILE=65535' }
    - { regexp: '^LimitNPROC=',   line: 'LimitNPROC=65535' }
    - { regexp: '^LimitCORE=',    line: 'LimitCORE=infinity' }
    - { regexp: '^LimitMEMLOCK=', line: 'LimitMEMLOCK=infinity' }
  register: php_service

- name: PHP configureation file transfer
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}/{{ item.src }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - { src: 'php.ini',      dest: '/etc/opt/remi/php{{ php_version }}' }
    - { src: 'php-fpm.conf', dest: '/etc/opt/remi/php{{ php_version }}' }
    - { src: 'www.conf',     dest: '/etc/opt/remi/php{{ php_version }}/php-fpm.d' }
  register: php_config