---
- name: Prometheus program binary transfer
  unarchive:
    src: 'php-fpm_exporter.tar.xz'
    dest: '/usr/local/bin'
    owner: 'nobody'
    group: 'nobody'
    mode: '0755'
  register: exporter_updated

- name: Prometheus configure file transfer
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
  with_items:
    - { src: 'php-fpm_exporter.default', dest: '/etc/default/php-fpm_exporter' }
    - { src: 'php-fpm_exporter.service', dest: '/lib/systemd/system/php-fpm_exporter.service' }
  register: exporter_config
