---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Allow php-fpm service port.
  firewalld:
    port: '{{ item }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop:
    - '{{ php_fpm_port }}'
    - '{{ php_fpm_exporter_port }}'
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
