---
- name: Creating php-fpm installs folder
  file:
    dest: '{{ php_path }}/remi'
    state: 'directory'

- name: Mount and bind php-fpm remi folder structure
  mount:
    src: '{{ php_path }}/remi'
    path: '/opt/remi'
    opts: 'bind'
    state: 'mounted'
    fstype: 'none'

- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Configure the firewall
  include: 'firewall.yml'

- name: Configuration the php-fpm
  include: 'configureation.yml'

- name: Reload the PHP-FPM service
  shell: echo ''
  notify: 'Ensure PHP-FPM service is enabled'
  when: php_updated is changed or php_config is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Include prometheus exporter tasks
  include: 'exporter.yml'
  when : exporter_is_install

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install
    - consul_public_register
