---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install the PHP dependents packages.
  yum:
    name: '{{ php_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Add Remi PHP YUM repositories.
  yum_repository:
    name: '{{ php_remi_repo_name }}'
    description: '{{ php_remi_repo_name }} RPM repository for Enterprise Linux'
    file: '{{ php_remi_repo_name }}'
    baseurl: '{{ php_remi_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Add Remi safe PHP YUM repositories.
  yum_repository:
    name: '{{ php_safe_repo_name }}'
    description: '{{ php_safe_repo_name }} RPM repository for additonal packages'
    file: '{{ php_safe_repo_name }}'
    baseurl: '{{ php_safe_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the PHP packages.
  yum:
    name: '{{ php_packages }}'
    enablerepo: '{{ php_remi_repo_name }},{{ php_safe_repo_name}}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: php_updated
  until: php_updated is succeeded
  retries: 5
  delay: 2
